### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports#10]
I put the configuration in workspace root package.json, this tool will not read it when format some file in workspace package.

**Comment by daidodo** [comment]
@tjx666, thanks for your feedback!

Sounds like you have multiple *package.json*  files in your project. But the plugin loads the first one found along the path: [source code](https://github.com/daidodo/format-imports/blob/main/src/lib/config/importSorter.ts#L55).

Could you share your workspace structure and the rationale behind your use case?

Thanks again!

**Comment by tjx666** [comment]
For example repo,  config format-import using package.json field in https://github.com/tjx666/electron-vue-vite-boilerplate/blob/master/package.json.

**Comment by daidodo** [comment]
I guess you have some common config and want to apply to all projects in the workspace.
You can create an *Import-sorter.json* in the workspace folder. All projects will use it as long as there is no such file in the project folders.

**Comment by tjx666** [comment]
Maybe this package should find package.json up to root directory util one contains `importSorter` field.

**Comment by daidodo** [comment]
@tjx666
I've added [monorepo support](https://github.com/daidodo/format-imports#monorepo-support) in the new release.
Please try it out!
Thanks!
