### ISSUE TITLE
Support format vue file

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports#11]
This extension is very useful to format ts/js file imports, but seems not support .vue yet. @daidodo

**Comment by daidodo** [comment]
Duplicate to https://github.com/daidodo/format-imports-vscode/issues/37.

**Comment by tjx666** [comment]
@daidodo @zddai any problems when implement vue support? Vue user amount is very large...

**Comment by daidodo** [comment]
I'm not familiar with Vue and don't have much time to ramp up.
If someone with experience can help, that'd be great!

**Comment by tjx666** [comment]
@daidodo 

1. match the script tag in vue file by https://regex101.com/r/zvwJ1B/1
2. format the script code
3. insert the result code back

**Comment by daidodo** [comment]
Many thanks for your PR (https://github.com/daidodo/format-imports/pull/19)!

Before shipping it to production, I still have a few questions:

* What are the supported `lang` values?
For example, if `<script lang="coffee">`, the plugin should skip. I assume they are default value (`js`?), plus `ts`. Are there other values (`tsx`, `jsx`)?

* How is *tsconfig.json* resolved? 
The plugin uses [TypeScript API](https://github.com/daidodo/format-imports/blob/main/src/lib/format/config/tsconfig.ts#L13) to find it for source file. I'm not sure if it's the same way in Vue?
Another minor question is: From [the doc](https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json), seems `jsx` [is always preserved](https://github.com/vuejs/tsconfig/blob/main/tsconfig.json#L9) in Vue, which means `import React from 'react'` should be kept. But in your test case it's removed. Am I missing something?

* From [these examples](https://vuejs.org/api/sfc-script-setup.html#using-components) it seems names can be imported in `<script>` and used in `<template>`. How to handle such cases?

I've added some test cases (which may fail) to reflect my questions.

**Comment by tjx666** [comment]
- vue only support js/jsx/ts/tsx

- tsconfig should be resolved same like rename the .vue extension to .ts. Vue jsx needn't react, jsx is not designed for react.

- seems I didn't implement the `remove unused imports` complented. In fact, variables can even be used in style block

**Comment by daidodo** [comment]
* Any doc or link?
* Any doc or link?

**Comment by tjx666** [comment]
- you should use volar which is a more recommend vue extension. use tsx/jsx is no warnings is my vscode + volar
- no, this is my thought, or it there any other posible?
- my work is busy recently, if you feel hard to implements it, you can just revert to last pr.

**Comment by daidodo** [comment]
* I believe [here](https://github.com/johnsoncodehk/volar/blob/master/vue-language-tools/vue-language-service/src/plugins/vue.ts#L67-L70) are all values for `<script lang>`.
* I implemented it based on your assumption. However, we can change it anytime if it's wrong.
* Many thanks for your works so far! There are no other critical features in the queue so no pressure. I tried to understand how Volar is working (because it gives correct *unused* warning messages) but got no luck. Will dive deeper later.

**Comment by daidodo** [comment]
@tjx666
I've released a new version to support Vue, with removing unused imports is disabled.

Please take a try and tell me if you find any issue. Thanks!

**Comment by tjx666** [comment]
simple try, and works good
