### ISSUE TITLE
Support group nodejs builtin modules

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports#14]
![image](https://user-images.githubusercontent.com/41773861/177957238-854132db-e8e5-4a47-a471-d97c051bc624.png)

One things may need to note is the recommand way to declare node builtin module is using `node:` prefix. So, I can using following config to group them:

```json
{
    "tsImportSorter.configuration.groupRules": [
        // note here!
        ["node:"],
        ["^[@][^/]", {}],
        [
            "^@(/|$)",
            "^actions?(/|$)",
            "^apis?(/|$)",
            "^assets(/|$)",
            "^components?(/|$)",
            "^helpers?(/|$)",
            "^pages?(/|$)",
            "^sagas?(/|$)",
            "^selectors?(/|$)",
            "^reducers?(/|$)",
            "^typings?(/|$)",
            "^utils(/|$)"
        ],
        { "flags": "named", "regex": "^[.]" },
        [
            { "flags": "scripts" },
            { "flags": "scripts", "regex": "[.]((css)|(less)|(scss))$" }
        ]
    ]
}
```

But for file which doesn't using `node:` prefix, there is no good way to group them.
Maybe this can be supported by add a new flags: `builtin`:

```json
{
    "tsImportSorter.configuration.groupRules": [
        ["flags": "builtin"],
        ["^[@][^/]", {}],
        [
            "^@(/|$)",
            "^actions?(/|$)",
            "^apis?(/|$)",
            "^assets(/|$)",
            "^components?(/|$)",
            "^helpers?(/|$)",
            "^pages?(/|$)",
            "^sagas?(/|$)",
            "^selectors?(/|$)",
            "^reducers?(/|$)",
            "^typings?(/|$)",
            "^utils(/|$)"
        ],
        { "flags": "named", "regex": "^[.]" },
        [
            { "flags": "scripts" },
            { "flags": "scripts", "regex": "[.]((css)|(less)|(scss))$" }
        ]
    ],
}
```

**Comment by daidodo** [comment]
Thanks for the feedback!

I guess the question is what are the built-in packages?
Do we need a hardcoded list and update every time node adds/removes a package? Or we probe in the file system and deal with different versions and paths?

**Comment by tjx666** [comment]
Well, we may just use the hardcode list like https://github.com/sindresorhus/builtin-modules#readme

**Comment by daidodo** [comment]
Good to know it!

A few thoughts:
* Instead of re-using `flags`, I'd add a new field, e.g. `domain` in [GroupRule](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#grouping-rule) because it's another dimension.

```ts
type Domain = 'nodejs-builtin' | 'non-nodejs-builtin' | 'domain-xxx' | 'non-domain-xxx' | ...;

interface GroupRule {
  //...
  domains?: Domain | Domain[];
};
```

* Each pair of `domain`/`non-domain` are complement.
* A group will accept an import only when it belongs to the defined domains. 
* When multiple domains are provided, the union of them is accepted.
* If not defined, all domains are accepted.

For ` 'nodejs-builtin' | 'non-nodejs-builtin'`, they need to consider both formats, e.g. `'fs'` and `'node:fs'`.

Please tell me if you have any comments.

Unfortunately, I won't be able to work on it recently so if you or anyone wants to help, that'd be great!

Thanks very much!

**Comment by daidodo** [comment]
@tjx666
Hi, this is now supported in [v7.5.0](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter) by [builtin](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#builtin) in GroupRule:

```js
{
  "groupRules": [
    {"builtin": true},
    ["^[@][^/]", {}],
    //....
  ]
}
```

In addition, you can add/remove `"node:"` for builtin modules with [nodeProtocol](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/Configuration.md#nodeprotocol):

```js
{
  "nodeProtocol": "always"
}
```

Please tell me if you have further questions.
Thanks!

**Comment by tjx666** [comment]
I test the latest version, and it works great. Thanks for your work!
