### ISSUE TITLE
Can't read eslintrc.js configuration

### ISSUE THREAD

**Issue by Nxt3** [daidodo/format-imports#15]
I noticed imports were being formatted incorrectly (using spaces instead of tabs) and it seems the extension isn't able to read this configuration:

```js
module.exports = {
	root: true,
	env: {
		browser: true
	},
	parser: '@typescript-eslint/parser',
	plugins: ['@typescript-eslint', 'jsdoc'],
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/eslint-recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:jsdoc/recommended'
	],
	rules: {
		indent: ['error', 'tab'],
		semi: ['error', 'always'],
		'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		'comma-dangle': ['warn', 'never'],
		'@typescript-eslint/explicit-module-boundary-types': [
			'off',
			{
				allowedNames: ['render', 'componentWillLoad']
			}
		]
	},
	ignorePatterns: ['*.js']
};
```

<img width="1349" alt="Screen Shot 2022-10-26 at 4 05 33 PM" src="https://user-images.githubusercontent.com/2940826/198129053-9766cff2-a308-47e1-a6cc-dd01454dfec1.png">

<img width="238" alt="Screen Shot 2022-10-26 at 4 22 04 PM" src="https://user-images.githubusercontent.com/2940826/198129236-66fad3cb-c2eb-4f0f-bb30-69b1058c0dad.png">

Using `v7.4.19` of format-imports.

**Comment by Nxt3** [comment]
I can't unfortunately. The repo is a monorepo using Rush.js so that might be the culprit.

[Microsoft has an example repo over here](https://github.com/microsoft/rush-example).


The real fix might be to add an option that disables all formatting and only performs the sorting. Using `codeActionsOnSave`, users can run the formatter of their choice after the sorting has occurred:

```jsonc
"[typescript]": {
    "editor.codeActionsOnSave": [
        "source.addMissingImports",
	"source.organizeImports.sortImports",
	"source.formatDocument", // in my case, prettier
	"source.fixAll.eslint"
    ]
}
```

otherwise, the tools fight each other when it comes to formatting.

**Comment by daidodo** [comment]
From the logs, the extension couldn't load ESLint from your *node_modules/* thus couldn't read *.eslintrc.js*. Any idea why was that?

Regarding code actions, have you tried your config? I think it might solve your problem because Prettier would change spaces to tabs, right?
