### ISSUE TITLE
Modules from URL are not formatted correctly

### ISSUE THREAD

**Issue by pting-me** [daidodo/format-imports#25]
**Describe the bug**

Modules from URL are not formatted correctly. This is syntax that is now supported by browsers, and is essential for Deno.

URLs should be preserved as:

```
https://*
```

But the formatter will strip the second slash:

```
https:/*
```

[SO discussion](https://stackoverflow.com/questions/34607252/es6-import-module-from-url)

[Detailed HTML spec description](https://html.spec.whatwg.org/multipage/webappapis.html#module-specifier-resolution)

**To Reproduce**
Is there a demo repo to reproduce the issue?
Yes
https://codesandbox.io/s/format-import-http-9nj1td

1. Create a string `import "https://esm.sh/clsx@1.2.1"`
2. Format using any method (the above case uses `formatSourceWithoutFile.sync`)
3. Notice the returned string strips the second slash: `import 'https:/esm.sh/clsx@1.2.1';`

**Expected behavior**

Expected two slashes preserved in import:

`import 'https://esm.sh/clsx@1.2.1';`

**Actual behavior**

Only one slash in import (as if `https` was a  protocol like `node`):

`import 'https:/esm.sh/clsx@1.2.1';`

**Comment by daidodo** [comment]
Thanks for the feedback!

Please try [the latest version](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter).

**Comment by pting-me** [comment]
Thanks for taking a look!

Unfortunately, the issue still exists, both in the codesandbox I linked, as well as in VSCode. I just updated the demo to `3.2.5`.
