### ISSUE TITLE
script imports always on top

### ISSUE THREAD

**Issue by GongT** [daidodo/format-imports#28]
**Describe the bug**

On the wiki, I see 
> Notes:
>
> Script imports will always be in front of other types of imports by default, unless explicitly defined in sub-groups.

But I can't find out how to "explicitly define", I have tried `{ "flags": "script" }` and `{ "subGroups": [{ "flags": "script" }] }` but it's not working.

**To Reproduce**

input file:
```ts
import { x } from "a";
import { y } from "b";
import "c"
```

groupRules:
```json
[
	{"regex": "^a"},
	{"flags": "script"},
	{"regex": "^b"}
]
```

**Expected behavior**

```ts
import { x } from "a";
import "c"
import { y } from "b";
```

**Actual behavior**

```ts
import "c"
import { x } from "a";
import { y } from "b";
```

**OS (please complete the following information):**

- OS: Linux
- Version: Fedora38

**Editor (please complete the following information):**

- Editor: VSCode
- Version: 1.80.0-insider

**Comment by daidodo** [comment]
"flags": "script<ins>s</ins>"
