### ISSUE TITLE
Taking very long, no idea why

### ISSUE THREAD

**Issue by jasonkuhrt** [daidodo/format-imports#3]
**Describe the bug**

Upon running `format-imports` it hangs

**To Reproduce**

Run `yarn format-imports` on a large project at the root.

Is there a debug mode?

**Comment by daidodo** [comment]
@jasonkuhrt - Thanks for the feedback!

Could you share your options after `format-imports`?

**Comment by daidodo** [comment]
I tested on [vscode](https://github.com/microsoft/vscode) source and it's slower than I thought:

```
$ time format-imports -c src/
Checked 2275 files, of which:
  340 files passed.
  1935 files have formatting issues.

real    6m35.349s
user    3m44.735s
sys     2m28.019s
```

Will try to address the issue. Thanks!

**Comment by daidodo** [comment]
Addressed an issue that *tsconfig.json* loading was super slow.

Published a new release v2.2.2.

```
Checked 2275 files, of which:
  340 files passed.
  1935 files have formatting issues.

real    1m43.383s
user    1m35.699s
sys     0m9.932s
```

Please try it and tell me if there are more issues.
Thanks!

**Comment by jasonkuhrt** [comment]
Thanks will try!

**Comment by daidodo** [comment]
@jasonkuhrt - I'll resolve this issue if you don't have any more questions.
