### ISSUE TITLE
Support multiple directories on CLI

### ISSUE THREAD

**Issue by jasonkuhrt** [daidodo/format-imports#5]
**Is your feature request related to a problem? Please describe.**
Need to format multiple directories

**Describe the solution you'd like**
`format-imports a b c`

This would align with `format-imports --check a b c`

**Describe alternatives you've considered**
none

**Comment by daidodo** [comment]
Thanks for the suggestion!

Could you instead use `format-imports a && format-imports b && format-imports c`?

The problem with multiple directories is that the `-o`/`--output` option won't work, which disables the ability to format and write to new files.

**Comment by jasonkuhrt** [comment]
That's what I currently do as a workaround yep.

**Comment by daidodo** [comment]
I'll close this if there is no update.
