### ISSUE TITLE
Copy trailing comma setting of prettier when in prettier-copy mode

### ISSUE THREAD

**Issue by jasonkuhrt** [daidodo/format-imports#7]
**Is your feature request related to a problem? Please describe.**

Prettier supports trailing comma style

```ts
import {
  createMockOutput,
  mockConsoleLog,
  MockOutput,
  resetBeforeEachTest,
  unmockConsoleLog,      // <-- prettier puts comma here, format-imports removes it
} from './__helpers'
```

**Describe the solution you'd like**
When asking format-imports to copy prettier, it should copy this trailing comma aspect of prettier too if enabled

**Describe alternatives you've considered**
none

**Additional context**
Only workaround right now seems to be to turn off trailing comma in prettier.

**Comment by daidodo** [comment]
Hi @jasonkuhrt, thanks for the feedback!

Could you share the following info to help investigation:
* Trigger the bug and send me your [debug logs](https://github.com/daidodo/format-imports-vscode/blob/master/CONTRIBUTING.md#debug-mode) if you use VSCode.
* Prettier config
* Plugin configs: [Configuration Resolution](https://github.com/daidodo/format-imports#configuration-resolution)

Thanks!

**Comment by jasonkuhrt** [comment]
prettier run:

![CleanShot 2021-06-25 at 13 08 49@2x](https://user-images.githubusercontent.com/284476/123461139-b2797300-d5b6-11eb-92fd-509a72d94041.png)

format-imports cli run:

![CleanShot 2021-06-25 at 13 09 03@2x](https://user-images.githubusercontent.com/284476/123461141-b4433680-d5b6-11eb-9526-9132454a31b5.png)

format-imports vsc run:

![CleanShot 2021-06-25 at 13 09 42@2x](https://user-images.githubusercontent.com/284476/123461144-b5746380-d5b6-11eb-9297-0d62e1f270b5.png)

**Comment by jasonkuhrt** [comment]
Just discovered `    "trailingComma": "multiLine"`

I think this issue is a feature request thing:

1. `trailingComma` option of `"prettier"`
2. General option called `"prettier": true` or something for those of us that just want to always be in sync with prettier rather than having to specify each setting one-by-one.

**Comment by daidodo** [comment]
This feature is already implemented. The plugin loads configs from prettier automatically, including traillingComma.
From the logs I suspect prettier API didn't find the config file, but I don't know why.

I can do more investigation if there is a demo project reproducing the issue.

**Comment by jasonkuhrt** [comment]
You should be able to repro with this project https://github.com/jasonkuhrt/template-typescript-lib. I can with it.

**Comment by daidodo** [comment]
I couldn't reproduce the issue on https://github.com/jasonkuhrt/template-typescript-lib.

What I did:
* Change *src/index.ts*:

```ts
import {
  createMockOutput,
  mockConsoleLog,
  MockOutput,
  resetBeforeEachTest,
  unmockConsoleLog,
} from './__helpers'

export * from '#utils'

export { createMockOutput, mockConsoleLog, MockOutput, resetBeforeEachTest, unmockConsoleLog }
```

* `yarn run format:imports`

```sh
yarn run v1.22.4
$ format-imports src && format-imports tests
No files modified.
No files modified.
✨  Done in 4.65s.
```

Result: The trailing comma is still there.

From the plugin logs I can see Prettier config was successfully loaded:

```log
[2021-06-27T08:48:20.807] [INFO] format-imports.loadPretConfig - Prettier API version: 2.2.1
[2021-06-27T08:48:20.824] [DEBUG] format-imports.loadPretConfig - Prettier config: { semi: false, singleQuote: true, printWidth: 110 }
```

**Comment by daidodo** [comment]
Sorry, I missed that you added the following in the plugin config, and can reproduce the issue now:

```json
    "trailingComma": "multiLine"
```

The root cause is my misunderstanding of `es5` option of [Prettier Options](https://prettier.io/docs/en/options.html#trailing-commas).
I'll fix it soon.
Thanks for the bug report!

**Comment by daidodo** [comment]
@jasonkuhrt 
Please try [v7.4.1](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter).
Thanks!

**Comment by jasonkuhrt** [comment]
Works! https://github.com/jasonkuhrt/template-typescript-lib/commit/47921dfe186fb5b887bd207aa0361868d824a16d

ty! 🙏
