### ISSUE TITLE
How to sort the import statement which not contains import name 

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports#8]
For Example, I want the `import './SaveNFTModal.less';` to be last line.

My configuration:

```jsonc
{
  // Wiki: https://github.com/daidodo/format-imports/wiki/Grouping-Rules
  "tsImportSorter.configuration.groupRules": [
    ["^[@]", {}],
    ["^api", "^components", "^features", "^style", "^util"],
    "^[.]"
  ],
  "tsImportSorter.configuration.wrappingStyle": {
    // Max binding names per line before wrapping for imports. 0 for no limit.
    "maxBindingNamesPerLine": 0,
    // Max default and binding names per line before wrapping for imports. 0 for no limit.
    "maxDefaultAndBindingNamesPerLine": 0,
    // Max binding names per line before wrapping for exports. 0 for no limit.
    "maxExportNamesPerLine": 0,
    // Max names on wrapped lines. 0 for no limit.
    "maxNamesPerWrappedLine": 0,
    // Whether to ignore trailing comments when counting line length.
    "ignoreComments": false
  },

  "tsImportSorter.configuration.sortRules": {
    // Sorting rule for import paths. Valid values are 'none' or an array.
    "paths": ["_", "aA"],

    // Sorting rule for imported/exported names. Valid values are 'none' or an array.
    "names": ["_", "aA"]
  }
}
```

![image](https://user-images.githubusercontent.com/41773861/123287364-46105c80-d541-11eb-9cdb-d99bba368caf.png)

**Comment by tjx666** [comment]
@daidodo

**Comment by daidodo** [comment]
Hi @tjx666, thanks for the feedback!

The imports are classified as script and named imports: [Types of Imports](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#types-of-imports)
And they are dealt with differently: [flags](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#flags)
Example: [How to customise script imports](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#ex-7-custom-groups-for-scripts)

Please tell me if you have further questions!

**Comment by tjx666** [comment]
Thanks for so awesome project!
